config-version: 2

name: "dbt_demo"
version: "3.0.0"
require-dbt-version: ">=1.5.0"


profile: "demo"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

packages-install-path: "dbt_packages"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Asia/Saigon"

seeds:
  dbt_demo:
    jaffle-data:
      +database: "logical-light-467105-p7"
      JAFFLE_SHOP_RAW:
        schema: JAFFLE_SHOP_RAW

models:
  dbt_demo:
    staging:
      +database: "logical-light-467105-p7"
      JAFFLE_SHOP_SERVING:
        materialized: table
        schema: JAFFLE_SHOP_SERVING
    marts:
      +database: "logical-light-467105-p7"
      JAFFLE_SHOP_MART:
        materialized: table
        schema: JAFFLE_SHOP_MART
