config-version: 2

name: "dbt_demo"
version: "3.0.0"
require-dbt-version: ">=1.5.0"


profile: "demo"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Asia/Saigon"

models:
  dbt_demo:
    staging:
      +materialized: view
    marts:
      +materialized: table
